export const UPDATE_LOGIN_STATUS: string = "UPDATE_LOGIN_STATUS";

export const UPDATE_IS_ON_SEARCH_SCREEN = "UPDATE_IS_ON_SEARCH_SCREEN";

export const UPDATE_SELECTED_ITEM = "UPDATE_SELECTED_ITEM";

export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
