export const UPDATE_SELECTED_ITEM: string = "UPDATE_SELECTED_ITEM";

export const UPDATE_SELECTED_SEARCH_PROP: string =
  "UPDATE_SELECTED_SEARCH_PROPERTY";

export const UPDATE_SEARCH_TERM: string = "UPDATE_SEARCH_TERM";

export const UPDATE_SELECTED_CHANGE_PROP: string =
  "UPDATE_SELECTED_CHANGE_PROP";

export const UPDATE_CHANGE_PROP_VALUE: string = "UPDATE_CHANGE_PROP_VALUE";

export const SELECT_DESELECT_DATA_ITEM: string = "SELECT_DESELECT_DATA_ITEM";

// Riki Text
export const SHOW_RIKI_TEXT: string = "SHOW_RIKI_TEXT";
