export const GET_ALL_SERVICE_ACTION: string = "GET_ALL_SERVICE_ACTION";

export const SEARCH_SERVICE_ACTION: string = "SEARCH_SERVICE_ACTION";

export const CHANGE_MULTIPLE_ITEMS_ACTION: string =
  "CHANGE_MULTIPLE_ITEMS_ACTION";

export const CHANGE_ITEM_ACTION: string = "CHANGE_ITEM_ACTION";
