export const UPDATE_SELECTED_ITEM: string = "UPDATE_SELECTED_ITEM";

export const UPDATE_SELECTED_SEARCH_PROP: string =
  "UPDATE_SELECTED_SEARCH_PROP";

export const UPDATE_SEARCH_TERM: string = "UPDATE_SEARCH_TERM";
